name: .deb test build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Code tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          ./hyperpixel4-backlight test

  build:
    name: Test build
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.get_changelog.outputs.changelog }}
      version: ${{ steps.get_version.outputs.version }}
      filename: ${{ steps.get_filename.outputs.filename }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          sudo apt update; sudo apt install -y debhelper build-essential
          make -C package build
      - name: Get changelog
        id: get_changelog
        run: |
          echo "::set-output name=changelog::`cd package && dpkg-parsechangelog --show-field Version`"
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::`cd package && dpkg-parsechangelog --show-field Changes`"
      - name: Get filename
        id: get_filename
        run: |
          echo "::set-output name=filename::`ls *.deb | head -n 1`"

  release:
    steps:
      - name: Test output
        run: |
          echo ${{needs.build.outputs.changelog}}
          echo ${{needs.build.outputs.version}}
          echo ${{needs.build.outputs.filename}}
